default_context:
  project_name: '{{ cookiecutter.project_name }}'
  project_slug: '{{ cookiecutter.project_slug }}'
  domain_main: '{{ cookiecutter.domain_main }}'
  domain_staging: '{{ cookiecutter.domain_staging }}'
  
  docker_swarm_stack_name_main: '{{ cookiecutter.docker_swarm_stack_name_main }}'
  docker_swarm_stack_name_staging: '{{ cookiecutter.docker_swarm_stack_name_staging }}'
  
  secret_key: '{{ cookiecutter.secret_key }}'
  first_superuser: '{{ cookiecutter.first_superuser }}'
  first_superuser_password: '{{ cookiecutter.first_superuser_password }}'
  backend_cors_origins: '{{ cookiecutter.backend_cors_origins }}'
  
  couchbase_user: '{{ cookiecutter.couchbase_user }}'
  couchbase_password: '{{ cookiecutter.couchbase_password }}'

  couchbase_sync_gateway_cors: '{{ cookiecutter.couchbase_sync_gateway_cors }}',
  couchbase_sync_gateway_user: '{{ cookiecutter.couchbase_sync_gateway_user }}',
  couchbase_sync_gateway_password: '{{ cookiecutter.couchbase_sync_gateway_password }}',
  
  traefik_constraint_tag: '{{ cookiecutter.traefik_constraint_tag }}'
  traefik_constraint_tag_staging: '{{ cookiecutter.traefik_constraint_tag_staging }}'
  traefik_public_network: '{{ cookiecutter.traefik_public_network }}'
  traefik_public_constraint_tag: '{{ cookiecutter.traefik_public_constraint_tag }}'
  
  flower_auth: '{{ cookiecutter.flower_auth }}'

  sentry_dsn: '{{ cookiecutter.sentry_dsn }}'
  
  docker_image_prefix: '{{ cookiecutter.docker_image_prefix }}'
  
  docker_image_backend: '{{ cookiecutter.docker_image_backend }}'
  docker_image_celeryworker: '{{ cookiecutter.docker_image_celeryworker }}'
  docker_image_frontend: '{{ cookiecutter.docker_image_frontend }}'
  docker_image_sync_gateway: '{{ cookiecutter.docker_image_sync_gateway }}'
  
  _copy_without_render:
    - frontend/src/**/*.html
    - frontend/src/**/*.vue
    - frontend/node_modules/*
  _template: ./
