version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=https://${DOMAIN}/api/v1/swagger/
  proxy:
    image: traefik:v1.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  flower:
    image: totem/celery-flower-docker
    environment:
      - FLOWER_BASIC_AUTH={{cookiecutter.flower_auth}}
